var MoveType = {
	MOVE: 'MOVE',
	MOVENC: 'MOVENC',
	MOVEEC: 'MOVEEC',
	MOVESC: 'MOVESC',
	SUPPORT: 'SUPPORT',
	HOLD: 'HOLD',
	CONVOY: 'CONVOY',
	BUILDARMY: 'BUILDARMY',
	BUILDFLEET: 'BUILDFLEET',
	BUILDFLEETSC: 'BUILDFLEETSC',
	BUILDFLEETNC: 'BUILDFLEETNC',
	DESTROY: 'DESTROY',
	RETREAT: 'RETREAT',
	LANDR0UTE: 'LANDROUTE',
	VIACONVOY: 'VIACONVOY'
}