var MoveType = {
	MOVE: 'MOVE',
	SUPPORT: 'SUPPORT',
	HOLD: 'HOLD',
	CONVOY: 'CONVOY',
	BUILDARMY: 'BUILDARMY',
	BUILDFLEET: 'BUILDFLEET',
	BUILDFLEETSC: 'BUILDFLEETSC',
	BUILDFLEETNC: 'BUILDFLEETNC',
	DESTROY: 'DESTROY',
	RETREAT: 'RETREAT'
}